<a href="https://colab.research.google.com/github/rakshitakanwar/ML/blob/main/day16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a= np.array([1,2,3])
print(a[0])
print(a[1])
print(a[-1])

1
2
3


In [ ]:
import numpy as np
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0,0]) #0 row par 0 column ya
print(a[1,2]) #1 row par 2 column ya index

1
6


In [3]:
#slicing
import numpy as np
a= np.array([10,20,30,40,50])
print(a[1:3])

[20 30]


In [4]:
import numpy as np
a= np.array([10,20,30,40,50])
print(a[0:4:2])

[10 30]


In [7]:
import numpy as np
m= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m[0:2,1:3]) #0-2 tk rows and 1-2 tk columns

[[2 3]
 [5 6]]


In [8]:
data=np.array([
[20,30000,1],
[25,50000,3],
[30,70000,5]
])
print(data[:,1])

[30000 50000 70000]


In [11]:
data=np.array([
[20,30000,1],
[25,50000,3],
[30,70000,5]
])
print(data[:,2])

[1 3 5]


In [17]:
import numpy as np
a= np.array([10,20,30,40,50])
print(a[0])
print(a[-1])
print(a[len(a)//2])

10
50
30


In [21]:
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[1,1])
print(arr[2,2])
print(arr[0])

5
9
[1 2 3]


In [31]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[0:6])
print(arr[-3:])
print(arr[0:len(arr):2])

[1 2 3 4 5 6]
[ 8  9 10]
[1 3 5 7 9]


In [33]:
data=np.array([
[25,50000],
[30,60000],
[35,70000],
[40,80000]
])
print(data[:,0])
print(data[:,1])

[25 30 35 40]
[50000 60000 70000 80000]


In [35]:
arr= np.array([1,2,3,4,5,6,7])
print(arr[[0,3,5]])

[1 4 6]
