In [ ]:
import numpy as np
a= np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
import numpy as np
a= np.array([1,2,3])
print(2*a)
print(type(a))

[2 4 6]
<class 'numpy.ndarray'>


In [ ]:
l=[1,2,3]
print(2*l)

[1, 2, 3, 1, 2, 3]


In [ ]:
import numpy as np
a= np.array(["apple","banana","orange"])
print(a)
print(type(a))

['apple' 'banana' 'orange']
<class 'numpy.ndarray'>


In [16]:
#1-d array
import numpy as np
a = np.array([10,20,30])
print(a)
print(a.ndim)

[10 20 30]
1


In [17]:
#2-d array
import numpy as np
a = np.array([[10,20,30],[4,5,6]])
print(a)
print(a.ndim)

[[10 20 30]
 [ 4  5  6]]
2


In [18]:
#3-d array
import numpy as np
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)
print(a.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


In [24]:
#2-d array
import numpy as np
a = np.array([[10,20,30],[4,5,6]])
print(a.shape) # 2 rows and 3 columns
print(a.size) #no of elements
print(a.dtype) #data type
print(type(a)) #N-dimensional array

(2, 3)
6
int64
<class 'numpy.ndarray'>


In [25]:
import numpy as np
a= np.array([[1.1,2.2],[3.3,4.4]])
print(a.dtype)

float64


In [27]:
import numpy as np
a= np.array([1,2,3])
print(a.itemsize) # each element size  (1 integer=8byte)
print(a.nbytes) # 3 element* 8byte=> 24

8
24


In [32]:
import numpy as np
a= np.zeros(3)
print(a)
print(a+5)

[0. 0. 0.]
[5. 5. 5.]


In [33]:
import numpy as np
a= np.zeros((3,4))
print(a)   # 3 rows and 4 columns

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [36]:
import numpy as np
a= np.ones(4)
print(a)
print(a*5)

[1. 1. 1. 1.]
[5. 5. 5. 5.]


In [39]:
import numpy as np
a= np.full((3,2),10)
print(a)

[[10 10]
 [10 10]
 [10 10]]


In [42]:
import numpy as np
a= np.eye(3) #3 ones in diagonal and rest all are 0 => identity matrix
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [43]:
import numpy as np
a= np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [45]:
import numpy as np
a=np.arange(1,11,2)
print(a)

[1 3 5 7 9]


In [47]:
import numpy as np
a= np.zeros((4,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [49]:
import numpy as np
a= np.arange(2,21,2)
print(a)

[ 2  4  6  8 10 12 14 16 18 20]


In [50]:
import numpy as np
a= np.full((2,3),9)
print(a)

[[9 9 9]
 [9 9 9]]
