<a href="https://colab.research.google.com/github/rakshitakanwar/day1.ipynb/blob/main/day8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#File Handling =>read,write and append

In [ ]:
from google.colab import drive
#drive.mount('/content/drive')
data= open("/content/drive/MyDrive/hello.txt", "r")
data.read()

Mounted at /content/drive


'hello file handling'

In [ ]:
data1= open("/content/drive/MyDrive/file1.csv", "r")
data1.read()

'name,roll no\ndheeraj,123\nkunal,1234\nabhishek,12345\npraveen,12356\nanjali,1234567'

In [ ]:
#write
data2= open("/content/drive/MyDrive/hello.txt", "w")
data2.write("Hello Rakshita Kanwar")

21

In [ ]:
data2 = open("/content/drive/MyDrive/hello.txt", "r")
print(data2.read())

Hello Rakshita Kanwar


In [ ]:
#read and append
data2 = open("/content/drive/MyDrive/hello.txt", "r")
print(data2.read())
data2 = open("/content/drive/MyDrive/hello.txt", "a")
data2.write(" Arya College")


Hello Rakshita Kanwar


13

In [ ]:
data2 = open("/content/drive/MyDrive/hello.txt", "r")
print(data2.read())

Hello Rakshita Kanwar Arya College


In [ ]:
#for csv file
data1= open("/content/drive/MyDrive/file1.csv", "r")
data1.read()


'name,roll no\ndheeraj,123\nkunal,1234\nabhishek,12345\npraveen,12356\nanjali,1234567'

In [ ]:
data1= open("/content/drive/MyDrive/file1.csv", "w")
data1.write("rakshita,40")

11

In [ ]:
data1= open("/content/drive/MyDrive/file1.csv", "r")
data1.read()

'rakshita,40'

In [ ]:
data1 = open("/content/drive/MyDrive/file1.csv", "a")
data1.write(" SAKSHI,123458")

data1= open("/content/drive/MyDrive/file1.csv", "r")
data1.read()


'rakshita,40\nSAKSHI,123458 SAKSHI,123458 SAKSHI,123458'

In [ ]:
data=open("hello.txt","r")
data.read()

'hello file handling'

Numpy => work for every element

In [ ]:
import numpy as np
#One-Dimensional
l=[10,20,30]
l*2

[10, 20, 30, 10, 20, 30]

In [ ]:
#Power of Numpy
arr = np.array(l)
arr*2

array([20, 40, 60])

In [ ]:
import numpy as np
arr= np.array([1,2,3,4])
print(arr[0])
print(arr[-1])

1
4


In [ ]:
import numpy as np
l=[10,20,30,40]
print(l)
print(type(l))

arr= np.array(l)
print(arr)
print(type(arr))

[10, 20, 30, 40]
<class 'list'>
[10 20 30 40]
<class 'numpy.ndarray'>


In [ ]:
#change value
import numpy as np
l=[10,20,30,40]
l[0]=100
l[-1]=200
print(l)
#numpy
arr= np.array(l)
arr[0]=300
arr[-1]=400
print(arr)

[100, 20, 30, 200]
[300  20  30 400]


In [ ]:
#value add
import numpy as np
l=[10,20,30,40]
#print(l+2)  add is not acceptable with list

arr= np.array(l)
print(arr+2)

[12 22 32 42]


In [ ]:
#arange in numpy
import numpy as np
arr= np.arange(5)
print(arr)

arr=np.arange(1,7,2)
print(arr)

[0 1 2 3 4]
[1 3 5]


In [ ]:
for i in range(5):
  print(i)

0
1
2
3
4


In [ ]:
#2-D
import numpy as np
print("list start")
l= [[1,2,3],[4,5,6]]
print(l)
print(l[0][0])
#numpy 2d
print("numpy start")
arr= np.array(l)
print(arr)
print(arr[0][1])


list start
[[1, 2, 3], [4, 5, 6]]
1
numpy start
[[1 2 3]
 [4 5 6]]
2


In [5]:
l= [[1,2,3],[4,5,6]]
print(l[0])

[1, 2, 3, 1, 2, 3]


In [7]:
import numpy as np
arr= np.array(l)
arr*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [10]:
import numpy as np
arr= np.array([[1,2,3],[4,5,6]])
print(arr[0])
print(arr[-1])
print(arr[0][0])
print(arr[0][1])

[1 2 3]
[4 5 6]
1
2


In [11]:
import numpy as np
l=[[1,2,3],[4,5,6]]
print(l)
print(type(l))

arr= np.array(l)
print(arr)
print(type(arr))

[[1, 2, 3], [4, 5, 6]]
<class 'list'>
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [12]:
#change value
import numpy as np
l=[[1,2,3],[4,5,6]]
l[0][0]=100
l[0][1]=200
print(l)
#numpy
arr= np.array(l)
arr[1][0]=300
arr[1][1]=400
print(arr)

[[100, 200, 3], [4, 5, 6]]
[[100 200   3]
 [300 400   6]]


In [13]:
#value add
import numpy as np
l=[[1,2,3],[4,5,6]]
#print(l+2)  add is not acceptable with list

arr= np.array(l)
print(arr+2)

[[3 4 5]
 [6 7 8]]


In [19]:
import numpy as np

arr = np.arange(1, 10).reshape(3, 3)   # 3 rows and 3 columns and 1 to 10 tak run karega its means 9

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
#3-D
import numpy as np
print("list start")
l= [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
print(l)
print(l[0])
print(l[0][0])
print(l[0][0][0])
#numpy 2d
print("numpy start")
arr= np.array(l)
print(arr)
print(arr[0][0][0])

list start
[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
[[1, 2, 3], [4, 5, 6]]
[1, 2, 3]
1
numpy start
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
1


In [30]:
l= [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
print(l[0])

#numpy
import numpy as np
arr= np.array(l)
arr*2

[[1, 2, 3], [4, 5, 6]]


array([[[ 2,  4,  6],
        [ 8, 10, 12]],

       [[14, 16, 18],
        [20, 22, 24]]])

In [31]:
import numpy as np
arr= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0])
print(arr[-1])
print(arr[0][0])
print(arr[0][1])

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[1 2 3]
[4 5 6]


In [33]:
import numpy as np
l=[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
print(l)
print(type(l))

arr= np.array(l)
print(arr)
print(type(arr))

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
<class 'list'>
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>


In [34]:
#change value
import numpy as np
l=[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
l[0][0][0]=100
l[0][0][1]=200
print(l)
#numpy
arr= np.array(l)
arr[1][0][0]=300
arr[1][0][1]=400
print(arr)

[[[100, 200, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
[[[100 200   3]
  [  4   5   6]]

 [[300 400   9]
  [ 10  11  12]]]


In [35]:
#value add
import numpy as np
l=[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
#print(l+2)  add is not acceptable with list

arr= np.array(l)
print(arr+2)

[[[ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]]]


In [36]:
import numpy as np
arr = np.arange(1, 25).reshape(2, 3, 4)     #2 blocks, 3 rows and 4 columns
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
